import { Component, OnInit } from '@angular/core';
import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);

import {
  AngularFirestore,
  AngularFirestoreCollection,
  AngularFirestoreDocument,
} from '@angular/fire/compat/firestore';
import { collection, query, where, onSnapshot } from 'firebase/firestore';
import { Dataservice } from '../../service';
import { ServiceService } from '../../service.service';
import { resetFakeAsyncZone } from '@angular/core/testing';
import { C } from 'chart.js/dist/chunks/helpers.core';
import { ArrayType } from '@angular/compiler';
import { GetalldataService } from '../../getalldata.service';
import { debounce, debounceTime, Observable } from 'rxjs';
@Component({
  selector: 'app-chart',
  templateUrl: './chart.component.html',
  styleUrls: ['./chart.component.css'],
})
export class ChartComponent implements OnInit {
  
  //Generated by typescript 1.8.10
  ngOnInit(): void {
    this.RenderChart();
  }
  constructor(public dv: ServiceService) {}
  RenderChart() {
    this.dv.getdata().subscribe((res: Dataservice[]) => {
      let arr3: any = [];
      let little: any = 0;
      let middle: any = 0;
      let high: any = 0;
      let none: any = 0;

      this.dv.getdata().subscribe((res: Dataservice[]) => {
        
        res.forEach(function (value) {
          if (value.gender == 'ชาย') {
            switch (value.status) {
              case 'ระดับน้อย': {
                little += 1;
                arr3[2] = little;
                // a.data1=little
                break;
              }
              case 'ระดับปานกลาง': {
                middle += 1;
                arr3[1] = middle;
                // a.data2=middle
                break;
              }
              case 'ระดับรุนแรง': {
                high += 1;
                arr3[0] = high;
                // a.data3=high
                break;
              }
              case 'ไม่มีอาการของโรคซึมเศร้าหรือมีอาการของโรคซึมเศร้าในปริมาณน้อย': {
                none += 1;
                arr3[3] = none;
                // a.data4=none
                break;
              }
            }
          }
        });
        let arr = [little, middle, high, none];
        console.log(arr);
        const ctx = document.getElementById('myChart');
        new Chart('myChart', {
          type: 'bar',
          data: {
            labels: [
              'ระดับรุนแรง',
              'ระดับปานกลาง',
              'ระดับน้อย',
              'ไม่มีอาการหรือมีน้อย',
            ],
            datasets: [
              {
                label: '',
                data: arr,
                backgroundColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(255, 159, 64, 1)',
                  'rgba(255, 205, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                ],
                borderWidth: 1,
              },
            ],
          },
          options: {
            scales: {
              y: {
                beginAtZero: true,
              },
            },
          },
        });
      });

     
    });
  }
}

//   const ctx = document.getElementById('myChart');
//   let data = this.data;
//   console.log(data);
//   new Chart('myChart', {
//     type: 'bar',
//     data: {
//       labels: [
//         'ระดับรุนแรง',
//         'ระดับปานกลาง',
//         'ระดับน้อย',
//         'ไม่มีอาการหรือมีน้อย',
//       ],
//       datasets: [
//         {
//           label: 'ช่วงอายุ20-25ปี',
//           data: data,
//           backgroundColor: [
//             'rgba(255, 99, 132, 1)',
//             'rgba(255, 159, 64, 1)',
//             'rgba(255, 205, 86, 1)',
//             'rgba(75, 192, 192, 1)',
//           ],
//           borderWidth: 1,
//         },
//       ],
//     },
//     options: {
//       scales: {
//         y: {
//           beginAtZero: true,
//         },
//       },
//     },
//   });
// }

// constructor(public dv: ServiceService) {}
// getalldata() {
// let arr3: any = [];
// let little:any= 0;
// let middle:any= 0;
// let high:any= 0;
// let none:any= 0;
// this.dv.getdata().subscribe((res: Dataservice[]) => {
//   this.data = res;
//     debounceTime(200)
//     res.forEach(function (value) {
//       if (value.gender == 'ชาย') {
//         switch (value.status) {
//           case 'ระดับน้อย': {
//             little += 1;
//             arr3[2] = little;
//             // a.data1=little
//             break;
//           }
//           case 'ระดับปานกลาง': {
//             middle += 1;
//             arr3[1] = middle;
//             // a.data2=middle
//             break;
//           }
//           case 'ระดับรุนแรง': {
//             high += 1;
//             arr3[0] = high;
//             // a.data3=high
//             break;
//           }
//           case 'ไม่มีอาการของโรคซึมเศร้าหรือมีอาการของโรคซึมเศร้าในปริมาณน้อย': {
//             none += 1;
//             arr3[3] = none;
//             // a.data4=none
//             break;
//           }
//         }
//       }
//     });

//     let arr = [little, middle, high, none];
//     console.log(typeof(arr))
//     // console.log(array)
//     return (arr)
//   });
// }

//   async caluser(){
//       let arr3:any=[]
//     let little: number = 0;
//       let middle: number = 0;
//       let high: number = 0;
//       let none: number = 0;
//       this.data.forEach(function (value) {
//         // console.log(value.status);
//         // if (value.gender == 'ชาย') {
//         //   switch (value.status) {
//         //     case 'ระดับน้อย': {
//         //       little += 1;
//         //       arr3[2] = little;
//         //       // a.data1=little
//         //       break;
//         //     }
//         //     case 'ระดับปานกลาง': {
//         //       middle += 1;
//         //       arr3[1] = middle;
//         //       // a.data2=middle
//         //       break;
//         //     }
//         //     case 'ระดับรุนแรง': {
//         //       high += 1;
//         //       arr3[0] = high;
//         //       // a.data3=high
//         //       break;
//         //     }
//         //     case 'ไม่มีอาการของโรคซึมเศร้าหรือมีอาการของโรคซึมเศร้าในปริมาณน้อย': {
//         //       none += 1;
//         //       arr3[3] = none;
//         //       // a.data4=none
//         //       break;
//         //     }

//         //   }

//         // }
//         // let array = [little, middle, high, none];

//         // return arr3
//         console.log()
//       });

// }

// let arr :any= [];
// let arr2: Array<number>;
// arr2 = [0, 0, 0, 0];
// var arr3 = new Array(4);
// let little: number = 0;
// let middle: number = 0;
// let high: number = 0;
// let none: number = 0;
// // this.data=res;
// // console.log(res.status)
// let a = this;
// res.forEach(function (value) {
//   // console.log(value.status);
//   if (value.gender == 'ชาย') {
//     switch (value.status) {
//       case 'ระดับน้อย': {
//         little += 1;
//         // arr3[2] = little;
//         // a.data1=little
//         break;
//       }
//       case 'ระดับปานกลาง': {
//         middle += 1;
//         // arr3[1] = middle;
//         // a.data2=middle
//         break;
//       }
//       case 'ระดับรุนแรง': {
//         high += 1;
//         // arr3[0] = high;
//          // a.data3=high
//         break;
//       }
//       case 'ไม่มีอาการของโรคซึมเศร้าหรือมีอาการของโรคซึมเศร้าในปริมาณน้อย': {
//         none += 1;
//         // arr3[3] = none;
//         // a.data4=none
//         break;
//       }
//     }
//   }
// });
// let array = [little, middle, high, none];
// console.log(array)
// return array;
