import { Component, OnInit } from '@angular/core';
import {Chart,registerables} from 'chart.js';
import { Dataservice } from '../../service';
import { ServiceService } from '../../service.service';
Chart.register(...registerables);
@Component({
  selector: 'app-chart-women',
  templateUrl: './chart-women.component.html',
  styleUrls: ['./chart-women.component.css']
})
export class ChartWomenComponent implements OnInit {

   //Generated by typescript 1.8.10
   ngOnInit(): void {
    this.RenderChart();
  }
  constructor(public dv: ServiceService) {}
  RenderChart() {
    this.dv.getdata().subscribe((res: Dataservice[]) => {
      let arr3: any = [];
      let little: any = 0;
      let middle: any = 0;
      let high: any = 0;
      let none: any = 0;

      this.dv.getdata().subscribe((res: Dataservice[]) => {
        res.forEach(function (value) {
          if (value.gender == 'หญิง') {
            switch (value.status) {
              case 'ระดับน้อย': {
                little += 1;
                arr3[2] = little;
                // a.data1=little
                break;
              }
              case 'ระดับปานกลาง': {
                middle += 1;
                arr3[1] = middle;
                // a.data2=middle
                break;
              }
              case 'ระดับรุนแรง': {
                high += 1;
                arr3[0] = high;
                // a.data3=high
                break;
              }
              case 'ไม่มีอาการของโรคซึมเศร้าหรือมีอาการของโรคซึมเศร้าในปริมาณน้อย': {
                none += 1;
                arr3[3] = none;
                // a.data4=none
                break;
              }
            }
          }
        });
        const ctx = document.getElementById('myChart');
        new Chart('myChart1', {
          type: 'bar',
          data: {
            labels: [
              'ระดับรุนแรง',
              'ระดับปานกลาง',
              'ระดับน้อย',
              'ไม่มีอาการหรือมีน้อย',
            ],
            datasets: [
              {
                label: '',
                data: arr3,
                backgroundColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(255, 159, 64, 1)',
                  'rgba(255, 205, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                ],
                borderWidth: 1,
              },
            ],
          },
          options: {
            scales: {
              y: {
                beginAtZero: true,
              },
            },
          },
        });
      });

     
    });
  }
}
